// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuG30zCQsPkKiWyybCmsNuT7XHUw2rAw0',
    appId: '1:871552481913:web:a9cafa73d215e3b31232a8',
    messagingSenderId: '871552481913',
    projectId: 'analytic-poc-37664',
    authDomain: 'analytic-poc-37664.firebaseapp.com',
    storageBucket: 'analytic-poc-37664.appspot.com',
    measurementId: 'G-RMGD0F7FSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWA4CHK5ggPyHoQI7jxuaoKSrp2TYdNqI',
    appId: '1:871552481913:android:06f9b04577aca3dc1232a8',
    messagingSenderId: '871552481913',
    projectId: 'analytic-poc-37664',
    storageBucket: 'analytic-poc-37664.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApE_HfOPRRaW8hqqG1aCKW_XfNLWocjuU',
    appId: '1:871552481913:ios:1e8a18218e75e0621232a8',
    messagingSenderId: '871552481913',
    projectId: 'analytic-poc-37664',
    storageBucket: 'analytic-poc-37664.appspot.com',
    iosBundleId: 'com.example.googleAnalyticPoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApE_HfOPRRaW8hqqG1aCKW_XfNLWocjuU',
    appId: '1:871552481913:ios:1e8a18218e75e0621232a8',
    messagingSenderId: '871552481913',
    projectId: 'analytic-poc-37664',
    storageBucket: 'analytic-poc-37664.appspot.com',
    iosBundleId: 'com.example.googleAnalyticPoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuG30zCQsPkKiWyybCmsNuT7XHUw2rAw0',
    appId: '1:871552481913:web:a5760bae7aaed3571232a8',
    messagingSenderId: '871552481913',
    projectId: 'analytic-poc-37664',
    authDomain: 'analytic-poc-37664.firebaseapp.com',
    storageBucket: 'analytic-poc-37664.appspot.com',
    measurementId: 'G-V5R1S3QWZX',
  );

}